#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd

# run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp

# build c++ progect via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vtop